### ISSUE TITLE
Python 3+ support

### ISSUE THREAD

**Issue by hjacobs** [alts/auto_meander#1]
Thanks for this treasure! I discovered Anni Albers' Meander via http://gallery.bananabanana.me/ and looked for Python code afterwards. I'm currently experimenting with your code and updated it for Python 3.9 support: https://codeberg.org/hjacobs/anni-albers-meander

I will probably change it to generate SVG files (for plotting / laser cutter), but I can do a PR to your repo to add Python 3 support if you want. Just let me know.

**Comment by alts** [comment]
Oh wow, I'm so glad to hear you've been using it! This has been a bit like throwing a message in a bottle into the sea and getting a response.

I'd really appreciate the Python 3 support! I'm also happy to add you as a collaborator on the repo if you'd like.

**Comment by hjacobs** [comment]
Pushed my changes including SVG generation. Here how such an SVG (23x23) looks after laser cutting:
![meander1](https://user-images.githubusercontent.com/510328/104123689-f7815400-534c-11eb-81cc-3ae69d68d064.jpg)
![meander2](https://user-images.githubusercontent.com/510328/104123688-f6e8bd80-534c-11eb-9753-8bd4ad42f48a.jpg)
